### Health Check
GET http://localhost:5003/api/health

### Create User
POST http://localhost:5003/api/user
Content-Type: application/json

{
  "email": "b@b.com",
  "username": "logo",
  "idp_uid": "abc45323"

}

### GET User
GET http://localhost:5003/api/user?id=USR01JZ1Y8EYZ8DVSC0R1AY9EJR41


### GET List of Users
GET http://localhost:5003/api/user/list

### Update User
PUT http://localhost:5003/user/USR01JZ1Y8EYZ8DVSC0R1AY9EJR41
Content-Type: application/json

{
  "email": "update@test.com",
  "username": "meowsers"
}


### Delete User
DELETE http://localhost:5003/api/user/USR01JYZ8XC32QMEGTR4RTXD86RGX